version: '3.8'
services:
  postgresql:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kelas
      POSTGRES_USER: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
